CREATE TABLE DashboardDB (
[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
[NAME] VARCHAR(15) NOT NULL,
[IMG_PATH] VARCHAR(50) NOT NULL
);

INSERT INTO DashboardDB (NAME, IMG_PATH) VALUES ('Board01', '/img/test1.png');
INSERT INTO DashboardDB (NAME, IMG_PATH) VALUES ('Board02', '/img/test2.png');